export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      visitors: {
        Row: {
          id: string;
          anonymous_id: string;
          first_source: string | null;
          first_medium: string | null;
          first_campaign: string | null;
          first_referrer: string | null;
          first_referrer_domain: string | null;
          is_ai_traffic: boolean;
          ai_referrer_source: string | null;
          latest_source: string | null;
          latest_medium: string | null;
          latest_campaign: string | null;
          latest_referrer: string | null;
          segment: string | null;
          visit_count: number;
          first_seen_at: string;
          last_seen_at: string;
          pages_viewed: string[];
          content_affinities: string[];
          device_type: string | null;
          browser: string | null;
          os: string | null;
          country: string | null;
          city: string | null;
          lead_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          anonymous_id: string;
          first_source?: string | null;
          first_medium?: string | null;
          first_campaign?: string | null;
          first_referrer?: string | null;
          first_referrer_domain?: string | null;
          is_ai_traffic?: boolean;
          ai_referrer_source?: string | null;
          latest_source?: string | null;
          latest_medium?: string | null;
          latest_campaign?: string | null;
          latest_referrer?: string | null;
          segment?: string | null;
          visit_count?: number;
          first_seen_at?: string;
          last_seen_at?: string;
          pages_viewed?: string[];
          content_affinities?: string[];
          device_type?: string | null;
          browser?: string | null;
          os?: string | null;
          country?: string | null;
          city?: string | null;
          lead_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          anonymous_id?: string;
          first_source?: string | null;
          first_medium?: string | null;
          first_campaign?: string | null;
          first_referrer?: string | null;
          first_referrer_domain?: string | null;
          is_ai_traffic?: boolean;
          ai_referrer_source?: string | null;
          latest_source?: string | null;
          latest_medium?: string | null;
          latest_campaign?: string | null;
          latest_referrer?: string | null;
          segment?: string | null;
          visit_count?: number;
          first_seen_at?: string;
          last_seen_at?: string;
          pages_viewed?: string[];
          content_affinities?: string[];
          device_type?: string | null;
          browser?: string | null;
          os?: string | null;
          country?: string | null;
          city?: string | null;
          lead_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      content_objects: {
        Row: {
          id: string;
          slug: string;
          title: string;
          subtitle: string | null;
          content_type: "article" | "case_study" | "video" | "guide" | "landing_page" | "snippet";
          body: string | null;
          excerpt: string | null;
          semantic_tags: string[];
          associated_offers: string[];
          target_segments: string[];
          seo_meta_id: string | null;
          featured_image_url: string | null;
          featured_video_url: string | null;
          view_count: number;
          unique_visitors: number;
          avg_time_on_page: number;
          conversion_count: number;
          engagement_score: number;
          status: "draft" | "published" | "archived";
          created_by: "human" | "content_agent" | "seo_agent";
          author_name: string;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          subtitle?: string | null;
          content_type?: "article" | "case_study" | "video" | "guide" | "landing_page" | "snippet";
          body?: string | null;
          excerpt?: string | null;
          semantic_tags?: string[];
          associated_offers?: string[];
          target_segments?: string[];
          seo_meta_id?: string | null;
          featured_image_url?: string | null;
          featured_video_url?: string | null;
          view_count?: number;
          unique_visitors?: number;
          avg_time_on_page?: number;
          conversion_count?: number;
          engagement_score?: number;
          status?: "draft" | "published" | "archived";
          created_by?: "human" | "content_agent" | "seo_agent";
          author_name?: string;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          subtitle?: string | null;
          content_type?: "article" | "case_study" | "video" | "guide" | "landing_page" | "snippet";
          body?: string | null;
          excerpt?: string | null;
          semantic_tags?: string[];
          associated_offers?: string[];
          target_segments?: string[];
          seo_meta_id?: string | null;
          featured_image_url?: string | null;
          featured_video_url?: string | null;
          view_count?: number;
          unique_visitors?: number;
          avg_time_on_page?: number;
          conversion_count?: number;
          engagement_score?: number;
          status?: "draft" | "published" | "archived";
          created_by?: "human" | "content_agent" | "seo_agent";
          author_name?: string;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      seo_meta: {
        Row: {
          id: string;
          title: string | null;
          description: string | null;
          canonical_url: string | null;
          og_image_url: string | null;
          schema_type: string;
          breadcrumb_path: Json | null;
          target_keyword: string | null;
          secondary_keywords: string[];
          keyword_cluster: string | null;
          current_rank: number | null;
          impressions_30d: number;
          clicks_30d: number;
          ctr_30d: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title?: string | null;
          description?: string | null;
          canonical_url?: string | null;
          og_image_url?: string | null;
          schema_type?: string;
          breadcrumb_path?: Json | null;
          target_keyword?: string | null;
          secondary_keywords?: string[];
          keyword_cluster?: string | null;
          current_rank?: number | null;
          impressions_30d?: number;
          clicks_30d?: number;
          ctr_30d?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string | null;
          description?: string | null;
          canonical_url?: string | null;
          og_image_url?: string | null;
          schema_type?: string;
          breadcrumb_path?: Json | null;
          target_keyword?: string | null;
          secondary_keywords?: string[];
          keyword_cluster?: string | null;
          current_rank?: number | null;
          impressions_30d?: number;
          clicks_30d?: number;
          ctr_30d?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      offers: {
        Row: {
          id: string;
          slug: string;
          name: string;
          tagline: string | null;
          description: string | null;
          price_display: string | null;
          price_cents: number | null;
          currency: string;
          billing_cycle: string | null;
          who_its_for: string | null;
          target_segments: string[];
          position_in_ladder: number | null;
          benefits: string[];
          cta_text: string | null;
          cta_url: string | null;
          featured_image_url: string | null;
          status: "active" | "paused" | "archived";
          view_count: number;
          click_count: number;
          conversion_count: number;
          conversion_rate: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          tagline?: string | null;
          description?: string | null;
          price_display?: string | null;
          price_cents?: number | null;
          currency?: string;
          billing_cycle?: string | null;
          who_its_for?: string | null;
          target_segments?: string[];
          position_in_ladder?: number | null;
          benefits?: string[];
          cta_text?: string | null;
          cta_url?: string | null;
          featured_image_url?: string | null;
          status?: "active" | "paused" | "archived";
          view_count?: number;
          click_count?: number;
          conversion_count?: number;
          conversion_rate?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          tagline?: string | null;
          description?: string | null;
          price_display?: string | null;
          price_cents?: number | null;
          currency?: string;
          billing_cycle?: string | null;
          who_its_for?: string | null;
          target_segments?: string[];
          position_in_ladder?: number | null;
          benefits?: string[];
          cta_text?: string | null;
          cta_url?: string | null;
          featured_image_url?: string | null;
          status?: "active" | "paused" | "archived";
          view_count?: number;
          click_count?: number;
          conversion_count?: number;
          conversion_rate?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          email: string;
          first_name: string | null;
          last_name: string | null;
          visitor_id: string | null;
          source: string | null;
          capture_page: string | null;
          status: "new" | "engaged" | "qualified" | "converted" | "lost";
          score: number;
          tags: string[];
          interested_offers: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          first_name?: string | null;
          last_name?: string | null;
          visitor_id?: string | null;
          source?: string | null;
          capture_page?: string | null;
          status?: "new" | "engaged" | "qualified" | "converted" | "lost";
          score?: number;
          tags?: string[];
          interested_offers?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string | null;
          last_name?: string | null;
          visitor_id?: string | null;
          source?: string | null;
          capture_page?: string | null;
          status?: "new" | "engaged" | "qualified" | "converted" | "lost";
          score?: number;
          tags?: string[];
          interested_offers?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      analytics_events: {
        Row: {
          id: string;
          visitor_id: string | null;
          anonymous_id: string;
          event_type: string;
          event_data: Json;
          page_url: string | null;
          page_slug: string | null;
          referrer: string | null;
          content_id: string | null;
          offer_id: string | null;
          visitor_segment: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          visitor_id?: string | null;
          anonymous_id: string;
          event_type: string;
          event_data?: Json;
          page_url?: string | null;
          page_slug?: string | null;
          referrer?: string | null;
          content_id?: string | null;
          offer_id?: string | null;
          visitor_segment?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          visitor_id?: string | null;
          anonymous_id?: string;
          event_type?: string;
          event_data?: Json;
          page_url?: string | null;
          page_slug?: string | null;
          referrer?: string | null;
          content_id?: string | null;
          offer_id?: string | null;
          visitor_segment?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      entities: {
        Row: {
          id: string;
          slug: string;
          name: string;
          entity_type: "organization" | "person" | "service" | "product" | "article" | "case_study" | "concept" | "event" | "place" | "thing";
          schema_type: string;
          schema_id: string | null;
          description: string | null;
          url: string | null;
          image_url: string | null;
          image_width: number | null;
          image_height: number | null;
          same_as: string[];
          properties: Json;
          knows_about: Json;
          appears_on_pages: string[];
          managed_by: string;
          last_audited_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          entity_type: "organization" | "person" | "service" | "product" | "article" | "case_study" | "concept" | "event" | "place" | "thing";
          schema_type: string;
          schema_id?: string | null;
          description?: string | null;
          url?: string | null;
          image_url?: string | null;
          image_width?: number | null;
          image_height?: number | null;
          same_as?: string[];
          properties?: Json;
          knows_about?: Json;
          appears_on_pages?: string[];
          managed_by?: string;
          last_audited_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          entity_type?: "organization" | "person" | "service" | "product" | "article" | "case_study" | "concept" | "event" | "place" | "thing";
          schema_type?: string;
          schema_id?: string | null;
          description?: string | null;
          url?: string | null;
          image_url?: string | null;
          image_width?: number | null;
          image_height?: number | null;
          same_as?: string[];
          properties?: Json;
          knows_about?: Json;
          appears_on_pages?: string[];
          managed_by?: string;
          last_audited_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      entity_relationships: {
        Row: {
          id: string;
          subject_id: string;
          predicate: string;
          object_id: string;
          properties: Json;
          weight: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          subject_id: string;
          predicate: string;
          object_id: string;
          properties?: Json;
          weight?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          subject_id?: string;
          predicate?: string;
          object_id?: string;
          properties?: Json;
          weight?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      personalization_rules: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          condition: Json;
          action: Json;
          page_patterns: string[];
          priority: number;
          status: "active" | "paused" | "archived";
          impressions: number;
          conversions: number;
          conversion_rate: number;
          created_by: string;
          last_evaluated_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          condition: Json;
          action: Json;
          page_patterns?: string[];
          priority?: number;
          status?: "active" | "paused" | "archived";
          impressions?: number;
          conversions?: number;
          conversion_rate?: number;
          created_by?: string;
          last_evaluated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          condition?: Json;
          action?: Json;
          page_patterns?: string[];
          priority?: number;
          status?: "active" | "paused" | "archived";
          impressions?: number;
          conversions?: number;
          conversion_rate?: number;
          created_by?: string;
          last_evaluated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_sequences: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          trigger_type: string;
          trigger_config: Json;
          steps: Json;
          target_segments: string[];
          status: "active" | "paused" | "archived";
          total_enrolled: number;
          total_completed: number;
          avg_open_rate: number;
          avg_click_rate: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          trigger_type: string;
          trigger_config?: Json;
          steps?: Json;
          target_segments?: string[];
          status?: "active" | "paused" | "archived";
          total_enrolled?: number;
          total_completed?: number;
          avg_open_rate?: number;
          avg_click_rate?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          trigger_type?: string;
          trigger_config?: Json;
          steps?: Json;
          target_segments?: string[];
          status?: "active" | "paused" | "archived";
          total_enrolled?: number;
          total_completed?: number;
          avg_open_rate?: number;
          avg_click_rate?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_sends: {
        Row: {
          id: string;
          lead_id: string;
          email_address: string;
          sequence_id: string | null;
          step_number: number | null;
          subject: string;
          template_id: string | null;
          resend_id: string | null;
          status: "pending" | "sent" | "failed" | "bounced";
          sent_at: string | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          email_address: string;
          sequence_id?: string | null;
          step_number?: number | null;
          subject: string;
          template_id?: string | null;
          resend_id?: string | null;
          status?: "pending" | "sent" | "failed" | "bounced";
          sent_at?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          email_address?: string;
          sequence_id?: string | null;
          step_number?: number | null;
          subject?: string;
          template_id?: string | null;
          resend_id?: string | null;
          status?: "pending" | "sent" | "failed" | "bounced";
          sent_at?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      email_events: {
        Row: {
          id: string;
          send_id: string;
          lead_id: string;
          event_type: "delivered" | "opened" | "clicked" | "bounced" | "complained" | "unsubscribed";
          event_data: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          send_id: string;
          lead_id: string;
          event_type: "delivered" | "opened" | "clicked" | "bounced" | "complained" | "unsubscribed";
          event_data?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          send_id?: string;
          lead_id?: string;
          event_type?: "delivered" | "opened" | "clicked" | "bounced" | "complained" | "unsubscribed";
          event_data?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      conversations: {
        Row: {
          id: string;
          visitor_id: string | null;
          lead_id: string | null;
          channel: "web_chat" | "whatsapp";
          external_id: string | null;
          started_on_page: string | null;
          visitor_segment: string | null;
          context: Json;
          status: "active" | "closed" | "archived";
          message_count: number;
          started_at: string;
          last_message_at: string;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          visitor_id?: string | null;
          lead_id?: string | null;
          channel?: "web_chat" | "whatsapp";
          external_id?: string | null;
          started_on_page?: string | null;
          visitor_segment?: string | null;
          context?: Json;
          status?: "active" | "closed" | "archived";
          message_count?: number;
          started_at?: string;
          last_message_at?: string;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          visitor_id?: string | null;
          lead_id?: string | null;
          channel?: "web_chat" | "whatsapp";
          external_id?: string | null;
          started_on_page?: string | null;
          visitor_segment?: string | null;
          context?: Json;
          status?: "active" | "closed" | "archived";
          message_count?: number;
          started_at?: string;
          last_message_at?: string;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          role: "user" | "assistant" | "system";
          content: string;
          token_count: number | null;
          model: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          role: "user" | "assistant" | "system";
          content: string;
          token_count?: number | null;
          model?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          role?: "user" | "assistant" | "system";
          content?: string;
          token_count?: number | null;
          model?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      media: {
        Row: {
          id: string;
          filename: string;
          mime_type: string;
          file_size: number | null;
          width: number | null;
          height: number | null;
          duration: number | null;
          r2_key: string;
          url: string;
          alt_text: string | null;
          caption: string | null;
          tags: string[];
          used_in_content: string[];
          uploaded_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          filename: string;
          mime_type: string;
          file_size?: number | null;
          width?: number | null;
          height?: number | null;
          duration?: number | null;
          r2_key: string;
          url: string;
          alt_text?: string | null;
          caption?: string | null;
          tags?: string[];
          used_in_content?: string[];
          uploaded_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          filename?: string;
          mime_type?: string;
          file_size?: number | null;
          width?: number | null;
          height?: number | null;
          duration?: number | null;
          r2_key?: string;
          url?: string;
          alt_text?: string | null;
          caption?: string | null;
          tags?: string[];
          used_in_content?: string[];
          uploaded_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      content_calendar: {
        Row: {
          id: string;
          title: string;
          search_query: string | null;
          target_keyword: string | null;
          keyword_cluster: string | null;
          intent_type: "how_to" | "comparison" | "definition" | "informational" | "commercial" | "transactional" | "listicle" | "case_study" | "opinion";
          priority: "high" | "medium" | "low";
          status: "planned" | "approved" | "writing" | "draft" | "published" | "archived";
          pillar_topic: string | null;
          topic_cluster: string | null;
          scheduled_publish_date: string | null;
          content_object_id: string | null;
          seo_meta_id: string | null;
          run_id: string | null;
          created_by: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          search_query?: string | null;
          target_keyword?: string | null;
          keyword_cluster?: string | null;
          intent_type?: "how_to" | "comparison" | "definition" | "informational" | "commercial" | "transactional" | "listicle" | "case_study" | "opinion";
          priority?: "high" | "medium" | "low";
          status?: "planned" | "approved" | "writing" | "draft" | "published" | "archived";
          pillar_topic?: string | null;
          topic_cluster?: string | null;
          scheduled_publish_date?: string | null;
          content_object_id?: string | null;
          seo_meta_id?: string | null;
          run_id?: string | null;
          created_by?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          search_query?: string | null;
          target_keyword?: string | null;
          keyword_cluster?: string | null;
          intent_type?: "how_to" | "comparison" | "definition" | "informational" | "commercial" | "transactional" | "listicle" | "case_study" | "opinion";
          priority?: "high" | "medium" | "low";
          status?: "planned" | "approved" | "writing" | "draft" | "published" | "archived";
          pillar_topic?: string | null;
          topic_cluster?: string | null;
          scheduled_publish_date?: string | null;
          content_object_id?: string | null;
          seo_meta_id?: string | null;
          run_id?: string | null;
          created_by?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      agent_logs: {
        Row: {
          id: string;
          agent: "content_agent" | "seo_agent" | "openclawd" | "analytics_agent" | "email_agent";
          action: string;
          description: string | null;
          status: "started" | "completed" | "failed";
          target_table: string | null;
          target_id: string | null;
          input_data: Json;
          output_data: Json;
          error_message: string | null;
          duration_ms: number | null;
          tokens_used: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent: "content_agent" | "seo_agent" | "openclawd" | "analytics_agent" | "email_agent";
          action: string;
          description?: string | null;
          status?: "started" | "completed" | "failed";
          target_table?: string | null;
          target_id?: string | null;
          input_data?: Json;
          output_data?: Json;
          error_message?: string | null;
          duration_ms?: number | null;
          tokens_used?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent?: "content_agent" | "seo_agent" | "openclawd" | "analytics_agent" | "email_agent";
          action?: string;
          description?: string | null;
          status?: "started" | "completed" | "failed";
          target_table?: string | null;
          target_id?: string | null;
          input_data?: Json;
          output_data?: Json;
          error_message?: string | null;
          duration_ms?: number | null;
          tokens_used?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {
      content_status: "draft" | "published" | "archived";
      content_type: "article" | "case_study" | "video" | "guide" | "landing_page" | "snippet";
      content_creator: "human" | "content_agent" | "seo_agent";
      offer_status: "active" | "paused" | "archived";
      lead_status: "new" | "engaged" | "qualified" | "converted" | "lost";
      entity_type: "organization" | "person" | "service" | "product" | "article" | "case_study" | "concept" | "event" | "place" | "thing";
      rule_status: "active" | "paused" | "archived";
      sequence_status: "active" | "paused" | "archived";
      send_status: "pending" | "sent" | "failed" | "bounced";
      email_event_type: "delivered" | "opened" | "clicked" | "bounced" | "complained" | "unsubscribed";
      conversation_channel: "web_chat" | "whatsapp";
      conversation_status: "active" | "closed" | "archived";
      message_role: "user" | "assistant" | "system";
      agent_name: "content_agent" | "seo_agent" | "openclawd" | "analytics_agent" | "email_agent";
      agent_action_status: "started" | "completed" | "failed";
      calendar_status: "planned" | "approved" | "writing" | "draft" | "published" | "archived";
      calendar_priority: "high" | "medium" | "low";
      intent_type: "how_to" | "comparison" | "definition" | "informational" | "commercial" | "transactional" | "listicle" | "case_study" | "opinion";
    };
  };
};

// Convenience type helpers
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
