-- Migration 010: Content Calendar
-- The content pipeline: topics are generated by the content strategy agent,
-- prioritized, approved, written, and published. This table tracks every stage.

create type calendar_status as enum (
  'planned',
  'approved',
  'writing',
  'draft',
  'published',
  'archived'
);

create type intent_type as enum (
  'how_to',
  'comparison',
  'definition',
  'informational',
  'commercial',
  'transactional',
  'listicle',
  'case_study',
  'opinion'
);

create type calendar_priority as enum ('high', 'medium', 'low');

create table content_calendar (
  id uuid primary key default uuid_generate_v4(),

  -- Topic info
  title text not null,                          -- proposed article title
  search_query text,                            -- the original audience search query
  target_keyword text,                          -- primary SEO keyword
  keyword_cluster text,                         -- references a cluster from keyword-clusters.md
  intent_type intent_type default 'informational',

  -- Prioritization
  priority calendar_priority default 'medium',

  -- Pipeline status
  status calendar_status default 'planned',

  -- Organization
  pillar_topic text,                            -- which of the 4 content pillars
  topic_cluster text,                           -- subtopic cluster within a pillar
  scheduled_publish_date date,                  -- when it should be published

  -- Links to published content
  content_object_id uuid references content_objects(id),  -- populated when article is written
  seo_meta_id uuid references seo_meta(id),               -- populated when SEO meta is created

  -- Batch tracking
  run_id text,                                  -- e.g. BB-CS-2026-03-25-01 or BB-TRENDS-2026-03-25

  -- Authorship
  created_by text default 'human',              -- human, content_agent, trend_scanner
  notes text,                                   -- for human review comments

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Indexes for common queries
create index idx_calendar_status on content_calendar(status);
create index idx_calendar_priority on content_calendar(priority);
create index idx_calendar_keyword_cluster on content_calendar(keyword_cluster);
create index idx_calendar_run_id on content_calendar(run_id);
create index idx_calendar_scheduled on content_calendar(scheduled_publish_date);

-- Prevent duplicate topics targeting the same keyword
create unique index idx_calendar_unique_topic
  on content_calendar(search_query, target_keyword)
  where status != 'archived';

create trigger calendar_updated_at
  before update on content_calendar
  for each row execute function update_updated_at();
